# Generated by Django 3.1.5 on 2021-01-23 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinics',
            name='field',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
