# Generated by Django 3.1.5 on 2021-01-24 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0002_clinics_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinics',
            name='max_patient',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
