# Generated by Django 3.1.5 on 2021-01-24 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0003_clinics_max_patient'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Queues',
        ),
    ]
