# Generated by Django 3.1.5 on 2021-01-23 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210122_2039'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clinicprofile',
            old_name='cell_phone',
            new_name='address',
        ),
        migrations.RemoveField(
            model_name='clinicprofile',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='clinicprofile',
            name='surname',
        ),
        migrations.AddField(
            model_name='clinicprofile',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='clinic_image'),
        ),
        migrations.AddField(
            model_name='clinicprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
