# Generated by Django 3.1.5 on 2021-01-24 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinics', '0004_delete_queues'),
    ]

    operations = [
        migrations.CreateModel(
            name='Queues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_patient', models.IntegerField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('clinic_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queue_name', to='clinics.clinics')),
            ],
        ),
    ]
