# Generated by Django 3.1.5 on 2021-01-24 07:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='queues',
            name='max_patient',
        ),
        migrations.AddField(
            model_name='queues',
            name='user',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, related_name='user_name', to='auth.user'),
            preserve_default=False,
        ),
    ]
