# Generated by Django 3.1.5 on 2021-01-24 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_auto_20210124_0731'),
    ]

    operations = [
        migrations.RenameField(
            model_name='queues',
            old_name='clinic_name',
            new_name='clinic',
        ),
    ]
