# Generated by Django 3.1.5 on 2021-01-24 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_auto_20210124_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queues',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
